{ config, pkgs, lib, ... }:

{
  # Pull in hardware config (auto-generated by the NixOS installer).
  imports = [
    ./hardware-configuration.nix
  ];

  ################################################################################
  # Bootloader / Kernel Modules
  ################################################################################

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.initrd.kernelModules = [ "i915" ];  # Use "amdgpu" for AMD or remove if unneeded

  ################################################################################
  # Basic System Settings
  ################################################################################

  networking.hostName = "SVArcade";
  networking.networkmanager.enable = true;
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 8080 8384 22000 ];
    allowedUDPPorts = [ 51820 7878 4242 22000 21027 ];
  };

  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";

  # Disable power management (prevent sleep)
  systemd.targets.sleep.enable = false;
  systemd.targets.suspend.enable = false;
  systemd.targets.hibernate.enable = false;
  systemd.targets.hybrid-sleep.enable = false;

  ################################################################################
  # X11 Configuration (auto-login + hide cursor + kiosk launch)
  ################################################################################

  services.xserver.enable = true;
  services.xserver.layout = "us";
  # services.xserver.videoDrivers = [ "intel" ];  # or "amdgpu" for AMD
  hardware.opengl.enable = true;
  hardware.opengl.driSupport32Bit = true;

  # Use LightDM display manager with auto-login
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "svarcade";

  # Disable any desktop environment; use a minimal window manager (Openbox)
  # services.xserver.desktopManager.default = "none";
  services.xserver.windowManager.openbox.enable = true;

  # The 'sessionCommands' run as soon as X logs in
  # We do 3 things:
  #   1) Disable X blanking (no sleep)
  #   2) Hide the mouse cursor (unclutter -idle 0)
  #   3) Pull from Git + run Godot
  services.xserver.displayManager.sessionCommands = ''

    ${pkgs.xorg.xrandr}/bin/xrandr --output HDMI-1 --mode 3840x2160
  
    # 1) Turn off screen blanking
    xset s off
    xset -dpms

    # 2) Hide the mouse cursor permanently
    unclutter -idle 0 &

    # 3) The kiosk script
    echo "Waiting for network..."
    TIMEOUT=60  # Maximum time in seconds to wait
    elapsed=0
    while ! ${pkgs.curl}/bin/curl --silent --head https://github.com/bezark/SVArcade-2025 > /dev/null; do
      sleep 2
      elapsed=$((elapsed+2))
      if [ $elapsed -ge $TIMEOUT ]; then
        echo "Network timeout reached. Continuing without network."
        break
      fi
    done
    echo "Network is up or timeout reached!"
    # echo "Waiting for network..."
    # until ${pkgs.curl}/bin/curl --silent --head https://github.com/bezark/SVArcade-2025 > /dev/null; do
    #   sleep 2
    # done
    # echo "Network is up!"

    if [ -d "/home/svarcade/SVArcade-2025/.git" ]; then
      ${pkgs.git}/bin/git -C /home/svarcade/SVArcade-2025 pull
    else
      ${pkgs.git}/bin/git clone https://github.com/bezark/SVArcade-2025.git /home/svarcade/SVArcade-2025
    fi

    ${pkgs.godot_4}/bin/godot4 --import --path /home/svarcade/SVArcade-2025/
    exec ${pkgs.godot_4}/bin/godot4 --path /home/svarcade/SVArcade-2025/
  '';

  ################################################################################
  # Audio with Pipewire/ALSA (no PulseAudio)
  ################################################################################

  hardware.pulseaudio.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  ################################################################################
  # System Packages
  ################################################################################

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    # Tools you already had
    rustdesk
    tmux
    screen
    nodejs_22
    temurin-bin-17
    git
    godot_4
    gdtoolkit_4
    wget
    github-desktop
    yazi
    broot
    helix

    # X11 cursor hider
    unclutter-xfixes
    xorg.xrandr

    # For the kiosk script
    curl
  ];

  ################################################################################
  # User Configuration
  ################################################################################

  users.users.svarcade = {
    isNormalUser = true;
    description = "SVArcade";
    # Add whatever groups you need (audio, wheel, etc.)
    extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "input" "video" ];
  };

  ################################################################################
  # Remote Access
  ################################################################################

  services.openssh.enable = true;
  services.tailscale.enable = true;   # if you use Tailscale

  ################################################################################
  # System State
  ################################################################################

  system.stateVersion = "24.11";  # or your current NixOS release
}
